plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
theme: jekyll-theme-cayman
title: Review MVC Callback
baseurl: "education-mvc-callback-2"
url: ""
